CREATE TABLE `ministock` (
  `id` VARCHAR(100) NOT NULL,
  `version` VARCHAR(50) NOT NULL,
  `title` VARCHAR(250) NOT NULL,
  `image` MEDIUMBLOB NOT NULL,
  `items` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = MyISAM;
